# ==================================== #
# docker.yml                           #
# canvas2's new distribution workflow  #
# ==================================== #

# Define Name
name: Docker Deploy

# Description:
#   This actions workflow was designed to compile our image and upload it to
#   the Github Container Registry.

#
# ===== [ Triggers ] ==========================================================
#

# This will only run if the following conditions are met:
# - Testing Suite was run and passed
# - We're on the "develop" branch

# NOTE: When we first release, this will be set to run on "main" branch.
#       Well, either that or on tagged version releases. I'm fine with
#       either. -A

on: 
  push:
    branches:
    - 'f/docker'
  workflow_run:
    workflows: ["Testing Suite"]
    types: 
    - completed
    branches:
    - 'develop'
    - 'f/docker'

#
# ===== [ Jobs ] ==============================================================
#

jobs:

  # 1.) Build Script
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    # 1.1.) Set up workspace
    - name: Set up workspace
      uses: actions/checkout@v1

    # 1.2) Auth with GHCR
    - name: Authenticate with GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}
      
    # 1.3) Set up Docker build
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # 1.4) Build and Push
    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/fsu-cop4521s/canvas2:latest
  